services:
  frontend:
    build: 
      context: ./frontend1
      dockerfile: Dockerfile

    container_name: lectio-frontend
    restart: always
    ports:
      - "3000:3000"

    
    networks:
      - lexion_internal_net 
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

    container_name: lectio-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - lexion_internal_net 
    depends_on:
      - mongo
      - minio


  minio:
    image: minio/minio:latest
    container_name: lection_minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    networks:
      - lexion_internal_net
    environment:
      MINIO_ROOT_USER: "${MINIO_USER?}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD?}"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  mongo:
    image: mongo:7
    container_name: mongo
    networks:
      - lexion_internal_net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME?}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD?}"
    volumes:
      - mongo_data:/data/db

volumes:
  minio_data:
  mongo_data:

networks:
   lexion_internal_net:


