services:
  minio:
    image: minio/minio:latest
    container_name: lection_minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    networks:
      - lexion_internal_net
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: crptx123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  minio_data:
  mongo_data:

networks:
   lexion_internal_net:


